============================= test session starts ==============================
platform darwin -- Python 3.10.6, pytest-7.4.4, pluggy-1.3.0 -- /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10
cachedir: .pytest_cache
rootdir: /Users/fenghuiting/Desktop/project-testing-team-i
collecting ... collected 4 items

secondTest.py::test_add_new_employee PASSED                              [ 25%]
secondTest.py::test_remove_manager_role PASSED                           [ 50%]
secondTest.py::test_zipcode FAILED                                       [ 75%]
secondTest.py::test_reset_db_without_password PASSED                     [100%]

=================================== FAILURES ===================================
_________________________________ test_zipcode _________________________________

browser_context = <BrowserContext browser=<Browser type=<BrowserType name=chromium executable_path=/Users/fenghuiting/Library/Caches/ms-playwright/chromium-1097/chrome-mac/Chromium.app/Contents/MacOS/Chromium> version=121.0.6167.57>>

    def test_zipcode(browser_context):
        context = browser_context
        page = context.new_page()
        context.tracing.start()
        page.goto('https://i.hr.dmerej.info/')
        page.get_by_role('link', name='List Employees').click()
        page.get_by_role('link', name='Edit').click()
        page.get_by_role('link', name='Update address').click()
        page.get_by_placeholder('Zip code').click()
>       page.press('Zip code', 'Enter')

secondTest.py:68: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/playwright/sync_api/_generated.py:11723: in press
    self._sync(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/playwright/_impl/_page.py:954: in press
    return await self._main_frame.press(**locals_to_params(locals()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/playwright/_impl/_frame.py:737: in press
    await self._channel.send("press", locals_to_params(locals()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py:63: in send
    return await self._connection.wrap_api_call(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py:495: in wrap_api_call
    return await cb()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <playwright._impl._connection.Channel object at 0x1090546d0>
method = 'press', params = {'key': 'Enter', 'selector': 'Zip code'}
return_as_dict = False

    async def inner_send(
        self, method: str, params: Optional[Dict], return_as_dict: bool
    ) -> Any:
        if params is None:
            params = {}
        callback = self._connection._send_message_to_server(
            self._object, method, _filter_none(params)
        )
        if self._connection._error:
            error = self._connection._error
            self._connection._error = None
            raise error
        done, _ = await asyncio.wait(
            {
                self._connection._transport.on_error_future,
                callback.future,
            },
            return_when=asyncio.FIRST_COMPLETED,
        )
        if not callback.future.done():
            callback.future.cancel()
>       result = next(iter(done)).result()
E       playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py:101: TimeoutError
=========================== short test summary info ============================
FAILED secondTest.py::test_zipcode - playwright._impl._errors.TimeoutError: T...
========================= 1 failed, 3 passed in 39.84s =========================
